In [1]:
import numpy as np
from sklearn.model_selection import train_test_split # деление данных на тренировочные и тестовые
from sklearn import metrics, linear_model # подсчет точности, линейная регрессия (тренируемая модель)

In [2]:

file = open("wifi_localization.txt") # исходные данные

WF = [] # качество сигнала для предсказания комнат 
RM = [] # номера комнат в соответствии с качеством сигнала WF

# первые семь значений строки - WF, сигнал, последнее - соответствующий ему номер комнаты RM
for s in file:
    WF.append(s.split()[:7])
    RM.append(s.split()[7:])

# преобразование в нампай 
WF = np.array(WF, dtype = int)
RM = np.array(RM, dtype = int)

In [3]:
WF_train, WF_test, RM_train, RM_test = train_test_split(WF, RM, random_state = 0) # разбиение на тренировочные и тестовые данные

In [4]:
logreg = linear_model.LogisticRegression(C = 10, solver = 'lbfgs', max_iter = 10000, multi_class = 'auto') # создание модели
logreg.fit(WF_train, RM_train) # тренировка модели

D:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=10, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=10000, multi_class='auto',
          n_jobs=None, penalty='l2', random_state=None, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

In [5]:
pred = logreg.predict(WF_test) # отправка тестовых данных в модель
print("Accuracy:", metrics.accuracy_score(RM_test, pred)) # подсчет точности предсказания

Accuracy: 0.986


In [10]:
room = []
# сравнение предсказанного с действительным
for i, j in enumerate(RM_test): 
    if pred[i] != j:
        room.append(i)

spTest = []
# сохранение ошибочных предсказаний
for i in room: 
    spTest.append(WF_test[i])  
spTest = np.array(spTest)

# вывод
for i in room: 
    print("Должно быть:", RM_test[i], " Получилось:", pred[i])
print()
print("Вероятность, что сеть в комнате")
print("[        1              2             3             4        ]")
print(logreg.predict_proba(spTest))

Должно быть: [2]  Получилось: 3
Должно быть: [2]  Получилось: 3
Должно быть: [3]  Получилось: 4
Должно быть: [2]  Получилось: 3
Должно быть: [2]  Получилось: 3
Должно быть: [3]  Получилось: 2
Должно быть: [3]  Получилось: 1

Вероятность, что сеть в комнате
[        1              2             3             4        ]
[[7.37704286e-11 6.27333241e-02 9.37266676e-01 1.78609223e-10]
 [3.70223220e-10 2.38350390e-01 7.61649608e-01 2.12072695e-09]
 [4.06575122e-06 6.59463297e-10 5.63299900e-02 9.43665944e-01]
 [2.06596920e-04 2.02033549e-01 7.97759853e-01 6.33555732e-10]
 [3.27977950e-10 2.34585504e-01 7.65414496e-01 3.51624364e-10]
 [1.30295567e-10 5.30934884e-01 4.69065116e-01 1.68221866e-11]
 [9.77427675e-01 2.72531172e-08 2.25705284e-02 1.76914746e-06]]
